# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ roman-actions ]
  pull_request:
    branches: [ main, devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Run tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: romancardenas/Group_E_Simulation_Lifecycle@v1.1.3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
